
Introduction

In [4]:
import tensorflow as tf




In [5]:
#create tensor with tf.constant
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#Check the number of dimensions of a tensor
scalar.ndim


0

In [7]:
vector =tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#Check the dimensions of our vector
vector.ndim

1

In [10]:
#create a matrix(has more than one dimension)
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim


2

In [16]:
#create another matrix
another_matrix=tf.constant([[10.,7.],[7.,19.],[6.,9.]
                        ],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 19.],
       [ 6.,  9.]], dtype=float16)>

In [26]:
tensor=tf.constant([[[1,2,3],
                    [2,3,4]],
                    [[3,4,5],
                     [3,4,5]],
                    [[4,5,5],
                     [1,3,1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [3, 4, 5]],

       [[4, 5, 5],
        [1, 3, 1]]], dtype=int32)>

In [27]:
tensor.ndim

3